{{- if .Values.persistentVolumeClaim.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "server.fullname" . }}
  labels:
{{- include "server.labels" . | nindent 4 }}
{{- if .Values.persistentVolumeClaim.labels }}
{{- toYaml .Values.persistentVolumeClaim.labels | nindent 4 }}
{{- end }}
  annotations:
{{- toYaml .Values.persistentVolumeClaim.annotations | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistentVolumeClaim.className | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
{{- toYaml .Values.persistentVolumeClaim.resources | nindent 6 }}
{{- end }}
