{{- if include "connector.enabled" . | eq "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "connector.fullname" . }}
  labels:
{{- include "connector.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - users
      - groups
    verbs:
      - impersonate
  - apiGroups: [""]
    resources:
      - pods
      - services
      - namespaces
    verbs:
      - list
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
      - bind
      - escalate
{{- end }}
