
{{- if include "connector.enabled" . | eq "true" }}
{{- $accessKey := default "" .Values.connector.config.accessKey -}}
{{- if or (not $accessKey) (and (not (hasPrefix "file:" $accessKey)) (not (hasPrefix "env:" $accessKey))) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-access-key
  labels:
{{- include "connector.labels" . | nindent 4 }}
data:
  access-key: {{ include "connector.accessKey" . | b64enc | quote }}
{{- end }}{{/* if not accessKey */}}
---
{{- if and (not .Values.connector.config.caCert) (not .Values.connector.config.caKey) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "connector.fullname" . }}-ca
  labels:
{{- include "connector.labels" . | nindent 4 }}
data:

{{- $secret := lookup "v1" "Secret" .Release.Namespace (printf "%s-ca" (include "connector.fullname" .)) }}
{{- if $secret.data }}
  ca.crt: |
{{- get $secret.data "ca.crt" | nindent 4 }}
  ca.key: |
{{- get $secret.data "ca.key" | nindent 4 }}

{{- else }}
{{- $ca := genCA "infra-connector" 3650 }}
  ca.crt: |
{{- $ca.Cert | b64enc | nindent 4 }}
  ca.key: |
{{- $ca.Key | b64enc | nindent 4 }}

{{- end }}{{/* if secret.data */}}
{{- end }}{{/* if not connector.config */}}
{{- end }}{{/* if server.enabled */}}
