{{- if include "connector.enabled" . | eq "true" }}
{{- $accessKey := default "" .Values.connector.config.accessKey -}}
{{- if or (not $accessKey) (and (not (hasPrefix "file:" $accessKey)) (not (hasPrefix "env:" $accessKey))) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-access-key
  labels:
{{- include "connector.labels" . | nindent 4 }}
data:
  access-key: {{ include "connector.accessKey" . | b64enc | quote }}
{{- end }}
---
{{- if and (not .Values.connector.config.caCert) (not .Values.connector.config.caKey) }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace (printf "%s-ca" (include "connector.fullname" .)) -}}
{{- $ca := genCA "infra-connector" 3650 -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "connector.fullname" . }}-ca
  labels:
{{- include "connector.labels" . | nindent 4 }}
data:
  ca.crt: |
{{- if $secret.data }}
{{- get $secret.data "ca.crt" | nindent 4 }}
{{- else }}
{{- $ca.Cert | b64enc | nindent 4 }}
{{- end }}
  ca.key: |
{{- if $secret.data }}
{{- get $secret.data "ca.key" | nindent 4 }}
{{- else }}
{{- $ca.Key | b64enc | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
