{{- if include "connector.enabled" . | eq "true" }}
{{- if .Values.connector.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "connector.serviceAccountName" . }}
  labels:
{{- include "connector.labels" . | nindent 4 }}
{{- with .Values.connector.serviceAccount.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
