{{- if .Values.engine.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "engine.fullname" . }}
  labels:
{{- include "engine.labels" . | nindent 4 }}
data:
  infra.yaml: |
{{- $accessKey := default "" .Values.engine.config.accessKey }}
{{- if and $accessKey (or (hasPrefix "file:" $accessKey) (hasPrefix "env:" $accessKey)) }}
    accessKey: {{ $accessKey }}
{{- else }}
    accessKey: file:/var/run/secrets/infrahq.com/access-key/access-key
{{- end }}

{{- if and .Values.server.enabled (not (hasKey .Values.engine.config "server")) }}
    server: {{ .Release.Name }}-server.{{ .Release.Namespace }}

{{- if (not (hasKey .Values.engine.config "skipTLSVerify")) }}
    # skip tls verify if we're connecting to an in-cluster server
    skipTLSVerify: true
{{- end }}
{{- end }}

{{- range $key, $val := omit .Values.engine.config "accessKey" }}
{{- if kindIs "invalid" $val }}
    # skipping invalid value: {{ $val }} ({{ kindOf $val }})
{{- else if kindIs "map" $val }}
    {{ $key }}:
{{- $val | toYaml | nindent 6 }}
{{- else if kindIs "slice" $val }}
    {{ $key }}:
{{- $val | toYaml | nindent 6 }}
{{- else if kindIs "string" $val }}
    {{ $key }}: {{ tpl $val $ }}
{{- else }}
    {{ $key }}: {{ $val }}
{{- end }}
{{- end }}
{{- end }}
