{{- if include "engine.enabled" . | eq "true" }}
{{- if .Values.engine.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "engine.serviceAccountName" . }}
  labels:
{{- include "engine.labels" . | nindent 4 }}
{{- with .Values.engine.serviceAccount.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
