{{- if include "server.enabled" . | eq "true" }}
{{- $adminAccessKey := default "" .Values.server.config.adminAccessKey -}}
{{- if and $adminAccessKey (not (hasPrefix "file:" $adminAccessKey)) (not (hasPrefix "env:" $adminAccessKey)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-admin-access-key
  labels:
{{- include "server.labels" . | nindent 4 }}
data:
  access-key: {{ .Values.server.config.adminAccessKey | b64enc | quote }}
{{- end }}
{{- end }}
