
{{- if include "server.enabled" . | eq "true" }}
{{- if (not .Values.server.config.tls) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "server.fullname" . }}-ca
  labels:
{{- include "server.labels" . | nindent 4 }}
data:

{{- $secret := lookup "v1" "Secret" .Release.Namespace (printf "%s-ca" (include "server.fullname" .)) -}}
{{- if $secret.data }}
  ca.crt: |
{{- get $secret.data "ca.crt" | nindent 4 }}
  ca.key: |
{{- get $secret.data "ca.key" | nindent 4 }}

{{- else }}
{{- $ca := genCA "Infra Server" 3650 }}
  ca.crt: |
{{- $ca.Cert | b64enc | nindent 4 }}
  ca.key: |
{{- $ca.Key | b64enc | nindent 4 }}

{{- end }}{{/* if secret.data */}}
{{- end }}{{/* if not tls */}}
{{- end }}{{/* if server.enabled */}}
---
{{- if include "server.enabled" . | eq "true" }}
{{- if not .Values.server.config.dbEncryptionKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "server.fullname" . }}-encryption-key
  labels:
{{- include "server.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
data:
{{- $secret := lookup "v1" "Secret" .Release.Namespace (printf "%s-encryption-key" (include "server.fullname" .)) -}}
{{- if $secret.data }}
  key: {{ $secret.data.key }}
{{- else }}
  key: {{ randAlphaNum 32 | b64enc }}
{{- end }}
{{- end }}
{{- end }}
