storage: 1Gi
engineApiKey: ""
config: null

pod:
  annotations: {}

telemetry:
  enabled: true

crashReporting:
  enabled: true

serviceAccount:
  create: true
  annotations: {}

image:
  repository: infrahq/infra
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  labels: {}
  annotations: {}
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443

ingress:
  enabled: false
  labels: {}
  annotations: {}
  servicePort: 80
  hosts: []
  tls: []
