run:
  go: 1.18
  skip-files:
    - internal/server/bindata_ui.go

  timeout: 5m

linters-settings:
  revive:
    rules:
      - name: var-naming
        arguments: [[ ID, API, HTTP ], []]
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/infrahq/infra)
  gocritic:
    disabled-checks:
      - singleCaseSwitch

linters:
  enable:
    - asciicheck
    - deadcode
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gci
    - gocritic
    - goimports
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - wastedassign
  disable:
    - scopelint
