env:
  # Disable CGO for now. This means binaries won't be able to run
  # "infra server" until we enable CGO at a later time.
  # TODO (https://github.com/infrahq/infra/issues/65)
  - CGO_ENABLED=0
  - GO111MODULE=on
  - BUILDVERSION_PRERELEASE={{ if index .Env "BUILDVERSION_PRERELEASE" }}{{ .Env.BUILDVERSION_PRERELEASE }}{{ end }}
  - BUILDVERSION_METADATA={{ if index .Env "BUILDVERSION_METADATA" }}{{ .Env.BUILDVERSION_METADATA }}{{ end }}
project_name: infra
builds:
  - id: infra
    ldflags:
      - -s -w
        -X github.com/infrahq/infra/internal.Branch={{ .Branch }}
        -X github.com/infrahq/infra/internal.Version={{ .RawVersion }}
        -X github.com/infrahq/infra/internal.Commit={{ .FullCommit }}
        -X github.com/infrahq/infra/internal.Date={{ .Date }}
        -X github.com/infrahq/infra/internal.Prerelease={{ .Env.BUILDVERSION_PRERELEASE }}
        -X github.com/infrahq/infra/internal.Metadata={{ .Env.BUILDVERSION_METADATA }}
    binary: infra
    main: ./main.go
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
nfpms:
  - id: packages
    package_name: infra
    file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Arch }}"
    builds:
      - infra
    vendor: Infra Technologies, Inc.
    homepage: https://infrahq.com
    maintainer: Infra Technologies, Inc. <contact@infrahq.com>
    license: Elastic License v2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    overrides:
      deb:
        file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
      apk:
        replacements:
          amd64: x86_64
          arm64: aarch64
      rpm:
        replacements:
          amd64: x86_64
          arm64: aarch64
archives:
  - id: zip
    format: zip
    replacements:
      amd64: x86_64
    files:
      - none*
checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
blobs:
  - provider: s3
    region: us-east-2
    bucket: releases.infrahq.com
    ids:
      - zip
      - packages
brews:
  - tap:
      owner: infrahq
      name: homebrew-tap
    commit_author:
      name: infra-ci
      email: contact@infrahq.com
    homepage: https://infrahq.com
    description: Infra
    url_template: "https://releases.infrahq.com/infra/{{ .Tag }}/{{ .ArtifactName }}"
    install: |
      bin.install "infra"
scoop:
  bucket:
    owner: infrahq
    name: scoop
  commit_author:
    name: infra-ci
    email: contact@infrahq.com
  homepage: https://infrahq.com
  description: Infra
  url_template: "https://releases.infrahq.com/infra/{{ .Tag }}/{{ .ArtifactName }}"
publishers:
  - name: gemfury
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.GEMFURY_TOKEN }}@push.fury.io/infrahq/
