FROM golang:1.18

RUN CGO_ENABLED=0 GOOS=linux go install -v -installsuffix cgo -a std
WORKDIR /go/src/github.com/infrahq/infra
COPY go.mod .
COPY go.sum .
RUN --mount=type=cache,id=gomod,target=/go/pkg/mod \
    --mount=type=cache,id=gobuild,target=/root/.cache/go-build \
    go mod download

COPY . .

RUN --mount=type=cache,id=gomod,target=/go/pkg/mod \
    --mount=type=cache,id=gobuild,target=/root/.cache/go-build \
    go build .

EXPOSE 80
EXPOSE 443
ENTRYPOINT ["./infra"]
CMD ["server"]
