openapi: 3.0.0
servers:
  - url: /v1
info:
  version: 0.1.0
  title: Infra API
  description: Infra REST API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: users
    description: Manage users
  - name: groups
    description: Manage groups
  - name: grants
    description: Manage grants
  - name: providers
    description: Manage identity providers
  - name: destinations
    description: Manage infrastructure destinations
  - name: tokens
    description: Manage infrastructure destination tokens
  - name: api-keys
    description: Manage administrator API keys
  - name: auth
    description: Manage user authentication
  - name: version
    description: Version
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /users:
    $ref: openapi/paths/users.yaml
  /users/{id}:
    $ref: openapi/paths/users@{id}.yaml
  /groups:
    $ref: openapi/paths/groups.yaml
  /groups/{id}:
    $ref: openapi/paths/groups@{id}.yaml
  /providers:
    $ref: openapi/paths/providers.yaml
  /providers/{id}:
    $ref: openapi/paths/providers@{id}.yaml
  /destinations:
    $ref: openapi/paths/destinations.yaml
  /destinations/{id}:
    $ref: openapi/paths/destinations@{id}.yaml
  /api-keys:
    $ref: openapi/paths/api-keys.yaml
  /api-keys/{id}:
    $ref: openapi/paths/api-keys@{id}.yaml
  /tokens:
    $ref: openapi/paths/tokens.yaml
  /grants:
    $ref: openapi/paths/grants.yaml
  /grants/{id}:
    $ref: openapi/paths/grants@{id}.yaml
  /login:
    $ref: openapi/paths/login.yaml
  /logout:
    $ref: openapi/paths/logout.yaml
  /version:
    $ref: openapi/paths/version.yaml
