{{- if include "ui.enabled" . | eq "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ui.fullname" . }}
  labels:
{{- include "ui.labels" . | nindent 4 }}
spec:
{{- if not .Values.ui.autoscaling.enabled }}
  replicas: {{ .Values.ui.replicas }}
{{- end }}
  selector:
    matchLabels:
{{- include "ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{- include "ui.podLabels" . | nindent 8 }}
      annotations:
{{- include "ui.podAnnotations" . | nindent 8 }}
    spec:
      automountServiceAccountToken: {{ .Values.ui.serviceAccount.automountServiceAccountToken }}
      serviceAccountName: {{ include "ui.serviceAccountName" . }}
      imagePullSecrets:
{{- include "ui.imagePullSecrets" . | nindent 8 }}
      securityContext:
{{- toYaml .Values.ui.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
{{- toYaml .Values.ui.securityContext | nindent 12 }}
          image: "{{ include "ui.image.repository" . }}:{{ include "ui.image.tag" . }}"
          imagePullPolicy: {{ include "ui.image.pullPolicy" . }}
          env:
{{- include "ui.env" . | nindent 12 }}
          envFrom:
{{- include "ui.envFrom" . | nindent 12 }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            successThreshold: {{ .Values.ui.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.ui.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.ui.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.ui.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.ui.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            successThreshold: {{ .Values.ui.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.ui.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.ui.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.ui.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.ui.readinessProbe.timeoutSeconds }}
          resources:
{{- toYaml .Values.ui.resources | nindent 12 }}
{{- with .Values.ui.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.ui.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.ui.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- end }}
