/*
Infra API

Infra REST API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// DestinationRequest struct for DestinationRequest
type DestinationRequest struct {
	Kind       DestinationKind        `json:"kind"`
	NodeID     string                 `json:"nodeID"`
	Name       string                 `json:"name"`
	Labels     []string               `json:"labels"`
	Kubernetes *DestinationKubernetes `json:"kubernetes,omitempty"`
}

// NewDestinationRequest instantiates a new DestinationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDestinationRequest(kind DestinationKind, nodeID string, name string, labels []string) *DestinationRequest {
	this := DestinationRequest{}
	this.Kind = kind
	this.NodeID = nodeID
	this.Name = name
	this.Labels = labels
	return &this
}

// NewDestinationRequestWithDefaults instantiates a new DestinationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDestinationRequestWithDefaults() *DestinationRequest {
	this := DestinationRequest{}
	return &this
}

// GetKind returns the Kind field value
func (o *DestinationRequest) GetKind() DestinationKind {
	if o == nil {
		var ret DestinationKind
		return ret
	}

	return o.Kind
}

// GetKindOK returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *DestinationRequest) GetKindOK() (*DestinationKind, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *DestinationRequest) SetKind(v DestinationKind) {
	o.Kind = v
}

// GetNodeID returns the NodeID field value
func (o *DestinationRequest) GetNodeID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeID
}

// GetNodeIDOK returns a tuple with the NodeID field value
// and a boolean to check if the value has been set.
func (o *DestinationRequest) GetNodeIDOK() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeID, true
}

// SetNodeID sets field value
func (o *DestinationRequest) SetNodeID(v string) {
	o.NodeID = v
}

// GetName returns the Name field value
func (o *DestinationRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOK returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DestinationRequest) GetNameOK() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DestinationRequest) SetName(v string) {
	o.Name = v
}

// GetLabels returns the Labels field value
func (o *DestinationRequest) GetLabels() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Labels
}

// GetLabelsOK returns a tuple with the Labels field value
// and a boolean to check if the value has been set.
func (o *DestinationRequest) GetLabelsOK() (*[]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Labels, true
}

// SetLabels sets field value
func (o *DestinationRequest) SetLabels(v []string) {
	o.Labels = v
}

// GetKubernetes returns the Kubernetes field value if set, zero value otherwise.
func (o *DestinationRequest) GetKubernetes() DestinationKubernetes {
	if o == nil || o.Kubernetes == nil {
		var ret DestinationKubernetes
		return ret
	}
	return *o.Kubernetes
}

// GetKubernetesOK returns a tuple with the Kubernetes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DestinationRequest) GetKubernetesOK() (*DestinationKubernetes, bool) {
	if o == nil || o.Kubernetes == nil {
		return nil, false
	}
	return o.Kubernetes, true
}

// HasKubernetes returns a boolean if a field has been set.
func (o *DestinationRequest) HasKubernetes() bool {
	if o != nil && o.Kubernetes != nil {
		return true
	}

	return false
}

// SetKubernetes gets a reference to the given DestinationKubernetes and assigns it to the Kubernetes field.
func (o *DestinationRequest) SetKubernetes(v DestinationKubernetes) {
	o.Kubernetes = &v
}

func (o DestinationRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["kind"] = o.Kind
	}
	if true {
		toSerialize["nodeID"] = o.NodeID
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["labels"] = o.Labels
	}
	if o.Kubernetes != nil {
		toSerialize["kubernetes"] = o.Kubernetes
	}
	return json.Marshal(toSerialize)
}

type NullableDestinationRequest struct {
	value *DestinationRequest
	isSet bool
}

func (v NullableDestinationRequest) Get() *DestinationRequest {
	return v.value
}

func (v *NullableDestinationRequest) Set(val *DestinationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDestinationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDestinationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDestinationRequest(val *DestinationRequest) *NullableDestinationRequest {
	return &NullableDestinationRequest{value: val, isSet: true}
}

func (v NullableDestinationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDestinationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
