/*
Infra API

Infra REST API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// ApiServiceCreateRequest struct for ApiServiceCreateRequest
type ApiServiceCreateRequest struct {
	Name string `json:"name"`
}

// NewApiServiceCreateRequest instantiates a new ApiServiceCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiServiceCreateRequest(name string) *ApiServiceCreateRequest {
	this := ApiServiceCreateRequest{}
	this.Name = name
	return &this
}

// NewApiServiceCreateRequestWithDefaults instantiates a new ApiServiceCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiServiceCreateRequestWithDefaults() *ApiServiceCreateRequest {
	this := ApiServiceCreateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *ApiServiceCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ApiServiceCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ApiServiceCreateRequest) SetName(v string) {
	o.Name = v
}

func (o ApiServiceCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableApiServiceCreateRequest struct {
	value *ApiServiceCreateRequest
	isSet bool
}

func (v NullableApiServiceCreateRequest) Get() *ApiServiceCreateRequest {
	return v.value
}

func (v *NullableApiServiceCreateRequest) Set(val *ApiServiceCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiServiceCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiServiceCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiServiceCreateRequest(val *ApiServiceCreateRequest) *NullableApiServiceCreateRequest {
	return &NullableApiServiceCreateRequest{value: val, isSet: true}
}

func (v NullableApiServiceCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiServiceCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
