/*
Infra API

Infra REST API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// User struct for User
type User struct {
	ID    string `json:"id"`
	Email string `json:"email" validate:"email,required"`
	// created time in seconds since 1970-01-01
	Created int64 `json:"created"`
	// updated time in seconds since 1970-01-01
	Updated int64 `json:"updated"`
	// timestamp of this users last interaction with Infra in seconds since 1970-01-01, 0 when a user has never connected
	LastSeen  int64       `json:"lastSeen"`
	Groups    *[]Group    `json:"groups,omitempty"`
	Grants    *[]Grant    `json:"grants,omitempty"`
	Providers *[]Provider `json:"providers,omitempty"`
}

// NewUser instantiates a new User object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUser(id string, email string, created int64, updated int64, lastSeen int64) *User {
	this := User{}
	this.ID = id
	this.Email = email
	this.Created = created
	this.Updated = updated
	this.LastSeen = lastSeen
	return &this
}

// NewUserWithDefaults instantiates a new User object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserWithDefaults() *User {
	this := User{}
	return &this
}

// GetID returns the ID field value
func (o *User) GetID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ID
}

// GetIDOK returns a tuple with the ID field value
// and a boolean to check if the value has been set.
func (o *User) GetIDOK() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ID, true
}

// SetID sets field value
func (o *User) SetID(v string) {
	o.ID = v
}

// GetEmail returns the Email field value
func (o *User) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOK returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *User) GetEmailOK() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *User) SetEmail(v string) {
	o.Email = v
}

// GetCreated returns the Created field value
func (o *User) GetCreated() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Created
}

// GetCreatedOK returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *User) GetCreatedOK() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *User) SetCreated(v int64) {
	o.Created = v
}

// GetUpdated returns the Updated field value
func (o *User) GetUpdated() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Updated
}

// GetUpdatedOK returns a tuple with the Updated field value
// and a boolean to check if the value has been set.
func (o *User) GetUpdatedOK() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Updated, true
}

// SetUpdated sets field value
func (o *User) SetUpdated(v int64) {
	o.Updated = v
}

// GetLastSeen returns the LastSeen field value
func (o *User) GetLastSeen() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LastSeen
}

// GetLastSeenOK returns a tuple with the LastSeen field value
// and a boolean to check if the value has been set.
func (o *User) GetLastSeenOK() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastSeen, true
}

// SetLastSeen sets field value
func (o *User) SetLastSeen(v int64) {
	o.LastSeen = v
}

// GetGroups returns the Groups field value if set, zero value otherwise.
func (o *User) GetGroups() []Group {
	if o == nil || o.Groups == nil {
		var ret []Group
		return ret
	}
	return *o.Groups
}

// GetGroupsOK returns a tuple with the Groups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetGroupsOK() (*[]Group, bool) {
	if o == nil || o.Groups == nil {
		return nil, false
	}
	return o.Groups, true
}

// HasGroups returns a boolean if a field has been set.
func (o *User) HasGroups() bool {
	if o != nil && o.Groups != nil {
		return true
	}

	return false
}

// SetGroups gets a reference to the given []Group and assigns it to the Groups field.
func (o *User) SetGroups(v []Group) {
	o.Groups = &v
}

// GetGrants returns the Grants field value if set, zero value otherwise.
func (o *User) GetGrants() []Grant {
	if o == nil || o.Grants == nil {
		var ret []Grant
		return ret
	}
	return *o.Grants
}

// GetGrantsOK returns a tuple with the Grants field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetGrantsOK() (*[]Grant, bool) {
	if o == nil || o.Grants == nil {
		return nil, false
	}
	return o.Grants, true
}

// HasGrants returns a boolean if a field has been set.
func (o *User) HasGrants() bool {
	if o != nil && o.Grants != nil {
		return true
	}

	return false
}

// SetGrants gets a reference to the given []Grant and assigns it to the Grants field.
func (o *User) SetGrants(v []Grant) {
	o.Grants = &v
}

// GetProviders returns the Providers field value if set, zero value otherwise.
func (o *User) GetProviders() []Provider {
	if o == nil || o.Providers == nil {
		var ret []Provider
		return ret
	}
	return *o.Providers
}

// GetProvidersOK returns a tuple with the Providers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetProvidersOK() (*[]Provider, bool) {
	if o == nil || o.Providers == nil {
		return nil, false
	}
	return o.Providers, true
}

// HasProviders returns a boolean if a field has been set.
func (o *User) HasProviders() bool {
	if o != nil && o.Providers != nil {
		return true
	}

	return false
}

// SetProviders gets a reference to the given []Provider and assigns it to the Providers field.
func (o *User) SetProviders(v []Provider) {
	o.Providers = &v
}

func (o User) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.ID
	}
	if true {
		toSerialize["email"] = o.Email
	}
	if true {
		toSerialize["created"] = o.Created
	}
	if true {
		toSerialize["updated"] = o.Updated
	}
	if true {
		toSerialize["lastSeen"] = o.LastSeen
	}
	if o.Groups != nil {
		toSerialize["groups"] = o.Groups
	}
	if o.Grants != nil {
		toSerialize["grants"] = o.Grants
	}
	if o.Providers != nil {
		toSerialize["providers"] = o.Providers
	}
	return json.Marshal(toSerialize)
}

type NullableUser struct {
	value *User
	isSet bool
}

func (v NullableUser) Get() *User {
	return v.value
}

func (v *NullableUser) Set(val *User) {
	v.value = val
	v.isSet = true
}

func (v NullableUser) IsSet() bool {
	return v.isSet
}

func (v *NullableUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUser(val *User) *NullableUser {
	return &NullableUser{value: val, isSet: true}
}

func (v NullableUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
