/*
Infra API

Infra REST API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// DestinationKubernetes struct for DestinationKubernetes
type DestinationKubernetes struct {
	CA       string `json:"ca" validate:"required"`
	Endpoint string `json:"endpoint" validate:"required"`
}

// NewDestinationKubernetes instantiates a new DestinationKubernetes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDestinationKubernetes(ca string, endpoint string) *DestinationKubernetes {
	this := DestinationKubernetes{}
	this.CA = ca
	this.Endpoint = endpoint
	return &this
}

// NewDestinationKubernetesWithDefaults instantiates a new DestinationKubernetes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDestinationKubernetesWithDefaults() *DestinationKubernetes {
	this := DestinationKubernetes{}
	return &this
}

// GetCA returns the CA field value
func (o *DestinationKubernetes) GetCA() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CA
}

// GetCAOK returns a tuple with the CA field value
// and a boolean to check if the value has been set.
func (o *DestinationKubernetes) GetCAOK() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CA, true
}

// SetCA sets field value
func (o *DestinationKubernetes) SetCA(v string) {
	o.CA = v
}

// GetEndpoint returns the Endpoint field value
func (o *DestinationKubernetes) GetEndpoint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Endpoint
}

// GetEndpointOK returns a tuple with the Endpoint field value
// and a boolean to check if the value has been set.
func (o *DestinationKubernetes) GetEndpointOK() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Endpoint, true
}

// SetEndpoint sets field value
func (o *DestinationKubernetes) SetEndpoint(v string) {
	o.Endpoint = v
}

func (o DestinationKubernetes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["ca"] = o.CA
	}
	if true {
		toSerialize["endpoint"] = o.Endpoint
	}
	return json.Marshal(toSerialize)
}

type NullableDestinationKubernetes struct {
	value *DestinationKubernetes
	isSet bool
}

func (v NullableDestinationKubernetes) Get() *DestinationKubernetes {
	return v.value
}

func (v *NullableDestinationKubernetes) Set(val *DestinationKubernetes) {
	v.value = val
	v.isSet = true
}

func (v NullableDestinationKubernetes) IsSet() bool {
	return v.isSet
}

func (v *NullableDestinationKubernetes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDestinationKubernetes(val *DestinationKubernetes) *NullableDestinationKubernetes {
	return &NullableDestinationKubernetes{value: val, isSet: true}
}

func (v NullableDestinationKubernetes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDestinationKubernetes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
