/*
Infra API

Infra REST API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// InfraAPITokenCreateResponse struct for InfraAPITokenCreateResponse
type InfraAPITokenCreateResponse struct {
	Token       string   `json:"token"`
	ID          string   `json:"id"`
	Created     int64    `json:"created"`
	Name        string   `json:"name"`
	Permissions []string `json:"permissions"`
	// token time to live before expiry in the form XhYmZs, for example 1h30m
	Ttl *string `json:"ttl,omitempty"`
}

// NewInfraAPITokenCreateResponse instantiates a new InfraAPITokenCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInfraAPITokenCreateResponse(token string, id string, created int64, name string, permissions []string) *InfraAPITokenCreateResponse {
	this := InfraAPITokenCreateResponse{}
	this.ID = id
	this.Created = created
	this.Name = name
	this.Permissions = permissions
	return &this
}

// NewInfraAPITokenCreateResponseWithDefaults instantiates a new InfraAPITokenCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInfraAPITokenCreateResponseWithDefaults() *InfraAPITokenCreateResponse {
	this := InfraAPITokenCreateResponse{}
	return &this
}

// GetToken returns the Token field value
func (o *InfraAPITokenCreateResponse) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOK returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *InfraAPITokenCreateResponse) GetTokenOK() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *InfraAPITokenCreateResponse) SetToken(v string) {
	o.Token = v
}

// GetID returns the ID field value
func (o *InfraAPITokenCreateResponse) GetID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ID
}

// GetIDOK returns a tuple with the ID field value
// and a boolean to check if the value has been set.
func (o *InfraAPITokenCreateResponse) GetIDOK() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ID, true
}

// SetID sets field value
func (o *InfraAPITokenCreateResponse) SetID(v string) {
	o.ID = v
}

// GetCreated returns the Created field value
func (o *InfraAPITokenCreateResponse) GetCreated() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Created
}

// GetCreatedOK returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *InfraAPITokenCreateResponse) GetCreatedOK() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *InfraAPITokenCreateResponse) SetCreated(v int64) {
	o.Created = v
}

// GetName returns the Name field value
func (o *InfraAPITokenCreateResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOK returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *InfraAPITokenCreateResponse) GetNameOK() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *InfraAPITokenCreateResponse) SetName(v string) {
	o.Name = v
}

// GetPermissions returns the Permissions field value
func (o *InfraAPITokenCreateResponse) GetPermissions() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Permissions
}

// GetPermissionsOK returns a tuple with the Permissions field value
// and a boolean to check if the value has been set.
func (o *InfraAPITokenCreateResponse) GetPermissionsOK() (*[]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Permissions, true
}

// SetPermissions sets field value
func (o *InfraAPITokenCreateResponse) SetPermissions(v []string) {
	o.Permissions = v
}

// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *InfraAPITokenCreateResponse) GetTtl() string {
	if o == nil || o.Ttl == nil {
		var ret string
		return ret
	}
	return *o.Ttl
}

// GetTtlOK returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfraAPITokenCreateResponse) GetTtlOK() (*string, bool) {
	if o == nil || o.Ttl == nil {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *InfraAPITokenCreateResponse) HasTtl() bool {
	if o != nil && o.Ttl != nil {
		return true
	}

	return false
}

// SetTtl gets a reference to the given string and assigns it to the Ttl field.
func (o *InfraAPITokenCreateResponse) SetTtl(v string) {
	o.Ttl = &v
}

func (o InfraAPITokenCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["token"] = o.Token
	}
	if true {
		toSerialize["id"] = o.ID
	}
	if true {
		toSerialize["created"] = o.Created
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["permissions"] = o.Permissions
	}
	if o.Ttl != nil {
		toSerialize["ttl"] = o.Ttl
	}
	return json.Marshal(toSerialize)
}

type NullableInfraAPITokenCreateResponse struct {
	value *InfraAPITokenCreateResponse
	isSet bool
}

func (v NullableInfraAPITokenCreateResponse) Get() *InfraAPITokenCreateResponse {
	return v.value
}

func (v *NullableInfraAPITokenCreateResponse) Set(val *InfraAPITokenCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableInfraAPITokenCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableInfraAPITokenCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInfraAPITokenCreateResponse(val *InfraAPITokenCreateResponse) *NullableInfraAPITokenCreateResponse {
	return &NullableInfraAPITokenCreateResponse{value: val, isSet: true}
}

func (v NullableInfraAPITokenCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInfraAPITokenCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
