/*
Infra API

Infra REST API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// LoginRequestInfra struct for LoginRequestInfra
type LoginRequestInfra struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required"`
}

// NewLoginRequestInfra instantiates a new LoginRequestInfra object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginRequestInfra(email string, password string) *LoginRequestInfra {
	this := LoginRequestInfra{}
	this.Email = email
	this.Password = password
	return &this
}

// NewLoginRequestInfraWithDefaults instantiates a new LoginRequestInfra object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginRequestInfraWithDefaults() *LoginRequestInfra {
	this := LoginRequestInfra{}
	return &this
}

// GetEmail returns the Email field value
func (o *LoginRequestInfra) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *LoginRequestInfra) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *LoginRequestInfra) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *LoginRequestInfra) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *LoginRequestInfra) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *LoginRequestInfra) SetPassword(v string) {
	o.Password = v
}

func (o LoginRequestInfra) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["email"] = o.Email
	}
	if true {
		toSerialize["password"] = o.Password
	}
	return json.Marshal(toSerialize)
}

type NullableLoginRequestInfra struct {
	value *LoginRequestInfra
	isSet bool
}

func (v NullableLoginRequestInfra) Get() *LoginRequestInfra {
	return v.value
}

func (v *NullableLoginRequestInfra) Set(val *LoginRequestInfra) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginRequestInfra) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginRequestInfra) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginRequestInfra(val *LoginRequestInfra) *NullableLoginRequestInfra {
	return &NullableLoginRequestInfra{value: val, isSet: true}
}

func (v NullableLoginRequestInfra) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginRequestInfra) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
