/*
Infra API

Infra REST API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// MachineAPIKey struct for MachineAPIKey
type MachineAPIKey struct {
	ApiKey  string      `json:"apiKey"`
	Id      string      `json:"id"`
	Created int64       `json:"created"`
	Name    string      `json:"name"`
	Kind    MachineKind `json:"kind"`
}

// NewMachineAPIKey instantiates a new MachineAPIKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMachineAPIKey(apiKey string, id string, created int64, name string, kind MachineKind) *MachineAPIKey {
	this := MachineAPIKey{}
	this.Id = id
	this.Created = created
	this.Name = name
	this.Kind = kind
	return &this
}

// NewMachineAPIKeyWithDefaults instantiates a new MachineAPIKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMachineAPIKeyWithDefaults() *MachineAPIKey {
	this := MachineAPIKey{}
	return &this
}

// GetApiKey returns the ApiKey field value
func (o *MachineAPIKey) GetApiKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value
// and a boolean to check if the value has been set.
func (o *MachineAPIKey) GetApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiKey, true
}

// SetApiKey sets field value
func (o *MachineAPIKey) SetApiKey(v string) {
	o.ApiKey = v
}

// GetId returns the Id field value
func (o *MachineAPIKey) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MachineAPIKey) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MachineAPIKey) SetId(v string) {
	o.Id = v
}

// GetCreated returns the Created field value
func (o *MachineAPIKey) GetCreated() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *MachineAPIKey) GetCreatedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *MachineAPIKey) SetCreated(v int64) {
	o.Created = v
}

// GetName returns the Name field value
func (o *MachineAPIKey) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MachineAPIKey) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MachineAPIKey) SetName(v string) {
	o.Name = v
}

// GetKind returns the Kind field value
func (o *MachineAPIKey) GetKind() MachineKind {
	if o == nil {
		var ret MachineKind
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *MachineAPIKey) GetKindOk() (*MachineKind, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *MachineAPIKey) SetKind(v MachineKind) {
	o.Kind = v
}

func (o MachineAPIKey) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["apiKey"] = o.ApiKey
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["created"] = o.Created
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["kind"] = o.Kind
	}
	return json.Marshal(toSerialize)
}

type NullableMachineAPIKey struct {
	value *MachineAPIKey
	isSet bool
}

func (v NullableMachineAPIKey) Get() *MachineAPIKey {
	return v.value
}

func (v *NullableMachineAPIKey) Set(val *MachineAPIKey) {
	v.value = val
	v.isSet = true
}

func (v NullableMachineAPIKey) IsSet() bool {
	return v.isSet
}

func (v *NullableMachineAPIKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMachineAPIKey(val *MachineAPIKey) *NullableMachineAPIKey {
	return &NullableMachineAPIKey{value: val, isSet: true}
}

func (v NullableMachineAPIKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMachineAPIKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
