/*
Infra API

Infra REST API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// InfraAPIToken struct for InfraAPIToken
type InfraAPIToken struct {
	ID          string   `json:"id"`
	Created     int64    `json:"created"`
	Name        string   `json:"name"`
	Permissions []string `json:"permissions"`
	// token time to live before expiry in the form XhYmZs, for example 1h30m
	Ttl *string `json:"ttl,omitempty"`
}

// NewInfraAPIToken instantiates a new InfraAPIToken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInfraAPIToken(id string, created int64, name string, permissions []string) *InfraAPIToken {
	this := InfraAPIToken{}
	this.ID = id
	this.Created = created
	this.Name = name
	this.Permissions = permissions
	return &this
}

// NewInfraAPITokenWithDefaults instantiates a new InfraAPIToken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInfraAPITokenWithDefaults() *InfraAPIToken {
	this := InfraAPIToken{}
	return &this
}

// GetID returns the ID field value
func (o *InfraAPIToken) GetID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ID
}

// GetIDOK returns a tuple with the ID field value
// and a boolean to check if the value has been set.
func (o *InfraAPIToken) GetIDOK() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ID, true
}

// SetID sets field value
func (o *InfraAPIToken) SetID(v string) {
	o.ID = v
}

// GetCreated returns the Created field value
func (o *InfraAPIToken) GetCreated() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Created
}

// GetCreatedOK returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *InfraAPIToken) GetCreatedOK() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *InfraAPIToken) SetCreated(v int64) {
	o.Created = v
}

// GetName returns the Name field value
func (o *InfraAPIToken) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOK returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *InfraAPIToken) GetNameOK() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *InfraAPIToken) SetName(v string) {
	o.Name = v
}

// GetPermissions returns the Permissions field value
func (o *InfraAPIToken) GetPermissions() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Permissions
}

// GetPermissionsOK returns a tuple with the Permissions field value
// and a boolean to check if the value has been set.
func (o *InfraAPIToken) GetPermissionsOK() (*[]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Permissions, true
}

// SetPermissions sets field value
func (o *InfraAPIToken) SetPermissions(v []string) {
	o.Permissions = v
}

// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *InfraAPIToken) GetTtl() string {
	if o == nil || o.Ttl == nil {
		var ret string
		return ret
	}
	return *o.Ttl
}

// GetTtlOK returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfraAPIToken) GetTtlOK() (*string, bool) {
	if o == nil || o.Ttl == nil {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *InfraAPIToken) HasTtl() bool {
	if o != nil && o.Ttl != nil {
		return true
	}

	return false
}

// SetTtl gets a reference to the given string and assigns it to the Ttl field.
func (o *InfraAPIToken) SetTtl(v string) {
	o.Ttl = &v
}

func (o InfraAPIToken) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.ID
	}
	if true {
		toSerialize["created"] = o.Created
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["permissions"] = o.Permissions
	}
	if o.Ttl != nil {
		toSerialize["ttl"] = o.Ttl
	}
	return json.Marshal(toSerialize)
}

type NullableInfraAPIToken struct {
	value *InfraAPIToken
	isSet bool
}

func (v NullableInfraAPIToken) Get() *InfraAPIToken {
	return v.value
}

func (v *NullableInfraAPIToken) Set(val *InfraAPIToken) {
	v.value = val
	v.isSet = true
}

func (v NullableInfraAPIToken) IsSet() bool {
	return v.isSet
}

func (v *NullableInfraAPIToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInfraAPIToken(val *InfraAPIToken) *NullableInfraAPIToken {
	return &NullableInfraAPIToken{value: val, isSet: true}
}

func (v NullableInfraAPIToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInfraAPIToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
