config: null
storage: 1Gi

config-path: /var/run/infra/config/infra.yaml
tls-cache: /var/run/infra/data/cache
db-file: /var/run/infra/data/infra.db
pgsql-dsn: ""

root-api-key: file:///var/run/secrets/infrahq.com/infra/root-api-key
engine-api-key: file:///var/run/secrets/infrahq.com/engine/engine-api-key

enable-telemetry: true
enable-crash-reporting: true

engine:
  apiKey: ""

pod:
  annotations: {}

serviceAccount:
  create: true
  annotations: {}

image:
  repository: infrahq/infra
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  labels: {}
  annotations: {}
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443

ingress:
  enabled: false
  labels: {}
  annotations: {}
  servicePort: 80
  hosts: []
  tls: []
