logLevel: info

config:
  rootAPIToken: kubernetes:infra/root-api-token
  engineAPIToken: kubernetes:infra-engine/api-token
  tlsCache: /var/run/infra/data/cache
  dbFile: /var/run/infra/data/infra.db
  dbEncryptionKey: infra/db-key
  keys:
    - kind: native
      secretProvider: kubernetes

storage: 1Gi

pod:
  annotations: {}

serviceAccount:
  create: true
  annotations: {}

image:
  repository: infrahq/infra
  tag: ""
  pullPolicy: IfNotPresent

engine:
  config:
    server: infra

service:
  type: LoadBalancer
  labels: {}
  annotations: {}
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    - name: metrics
      port: 9090
      targetPort: 9090

ingress:
  enabled: false
  labels: {}
  annotations: {}
  servicePort: 80
  hosts: []
  tls: []
