config: null
storage: 1Gi

configPath: /var/run/infra/config/infra.yaml
tlsCache: /var/run/infra/data/cache
dbFile: /var/run/infra/data/infra.db
pg:
  host: ""
  port: 5432
  db-name: postgres
  user: ""
  password: ""
  parameters: ""


rootAPIKey: file:/var/run/secrets/infrahq.com/infra/root-api-key
engineAPIKey: file:/var/run/secrets/infrahq.com/engine/engine-api-key

enableTelemetry: true
enableCrashReporting: true

# unset engine.apiKey so the subchart does not template another secret
engine:
  apiKey: ""

pod:
  annotations: {}

serviceAccount:
  create: true
  annotations: {}

image:
  repository: infrahq/infra
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  labels: {}
  annotations: {}
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443

ingress:
  enabled: false
  labels: {}
  annotations: {}
  servicePort: 80
  hosts: []
  tls: []
