apiVersion: v1
kind: Namespace
metadata:
  name: infra
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra
  namespace: infra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infra
rules:
  - apiGroups: [""]
    resources:
      - users
      - groups
    verbs:
      - impersonate
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
      - bind
      - escalate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infra
subjects:
- kind: ServiceAccount
  name: infra
  namespace: infra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: infra
---
apiVersion: v1
kind: Service
metadata:
  name: infra
  namespace: infra
  labels:
    app: infra
spec:
  type: LoadBalancer
  selector:
    app: infra
  ports:
    - name: https
      port: 443
      targetPort: 443
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: infra
  namespace: infra
spec:
  selector:
    matchLabels:
      app: infra
  replicas: 1
  serviceName: infra
  template:
    metadata:
      labels:
        app: infra
    spec:
      serviceAccountName: infra
      automountServiceAccountToken: true
      containers:
        - name: server
          image: infrahq/infra:dev
          imagePullPolicy: Never
          args: ["server", "-c", "/var/run/infra/config/infra.yaml", "--db", "/var/run/infra/data/infra.db", "--tls-cache", "/var/run/infra/data/cache", "--ui"]
          ports:
            - containerPort: 443
          volumeMounts:
            - name: data
              mountPath: /var/run/infra/data
            - name: config
              mountPath: /var/run/infra/config
            - name: secrets
              mountPath: /var/run/infra/secrets
      volumes:
        - name: config
          configMap:
            name: infra
            optional: true
        - name: secrets
          secret:
            secretName: infra
            optional: true
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
