apiVersion: v1
kind: Namespace
metadata:
  name: infra
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-serviceaccount
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra
  namespace: infra
  labels:
    app: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra
  template:
    metadata:
      labels:
        app: infra
    spec:
      containers:
      - name: server
        image: infrahq/infra
        imagePullPolicy: Never
        ports:
        - containerPort: 3090
