---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "infra.fullname" . }}
  labels:
{{- include "infra.labels" . | nindent 4 }}
data:
{{- if .Values.config }}
{{- if kindIs "map" .Values.config }}
  infra.yaml: |
  {{- toYaml .Values.config | nindent 4 }}
{{- else if kindIs "string" .Values.config }}
  infra.yaml:
  {{- toYaml .Values.config | nindent 4 }}
{{- end }}
{{- end }}

  config.yaml: |
{{- $options := list "config-path" "db-file" "pgsql-dsn" "tls-cache" }}
{{- $options = list "root-api-key" "engine-api-key" | concat $options }}
{{- $options = list "enable-ui" "ui-proxy" | concat $options }}
{{- $options = list "providers-sync-interval" "destinations-sync-interval" | concat $options }}
{{- $options = list "enable-telemetry" "enable-crash-reporting" | concat $options }}
{{- range $options }}
  {{- if hasKey $.Values . }}
    {{ . }}: {{ get $.Values . }}
  {{- end }}
{{- end }}
