---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "infra.fullname" . }}
  labels:
{{- include "infra.labels" . | nindent 4 }}
data:
{{- if .Values.config }}
{{- if kindIs "map" .Values.config }}
  infra.yaml: |
  {{- toYaml .Values.config | nindent 4 }}
{{- else if kindIs "string" .Values.config }}
  infra.yaml:
  {{- toYaml .Values.config | nindent 4 }}
{{- end }}
{{- end }}

  config.yaml: |
{{- $options := list "configPath" "dbFile" "pg" "tlsCache" }}
{{- $options = list "rootAPIKey" "engineAPIKey" | concat $options }}
{{- $options = list "enableUI" "uiProxy" | concat $options }}
{{- $options = list "providersSyncInterval" "destinationsSyncInterval" | concat $options }}
{{- $options = list "enableTelemetry" "enableCrashReporting" | concat $options }}
{{- range $options }}
  {{- if hasKey $.Values . }}
    {{ . | kebabcase }}: {{ get $.Values . | toJson }}
  {{- end }}
{{- end }}
