apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "infra.fullname" . }}
  labels:
{{- include "infra.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
