{{- $config := omit .Values.config "rootAPIToken" "engineAPIToken" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "infra.fullname" . }}
  labels:
{{- include "infra.labels" . | nindent 4 }}
data:
  config.yaml: |
    rootAPIToken: file:/var/run/secrets/infrahq.com/infra/root-api-token
    engineAPIToken: file:/var/run/secrets/infrahq.com/engine/engine-api-token
    {{- toYaml $config | nindent 4 }}
