{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "infra.fullname" . }}
  labels:
{{- include "infra.labels" . | nindent 4 }}
data:
{{- if kindIs "map" .Values.config }}
  infra.yaml: |
  {{- toYaml .Values.config | nindent 4 }}
{{- else if kindIs "string" .Values.config }}
  infra.yaml:
  {{- toYaml .Values.config | nindent 4 }}
{{- end }}
{{- end }}
