apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "infra.fullname" . }}
  labels:
{{- include "infra.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
{{- include "infra.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
{{- include "infra.selectorLabels" . | nindent 8 }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
{{- with .Values.pod.annotations }}
  {{- toYaml . | nindent 8 }}
{{- end }}
    spec:
      automountServiceAccountToken: true
      serviceAccountName: {{ include "infra.serviceAccountName" . }}
      dnsPolicy: ClusterFirst
{{- with .Values.image.pullSecrets }}
      imagePullSecrets:
  {{- range . }}
        - name: {{ . }}
  {{- end }}
{{- end }}
      containers:
        - name: infra
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [start, -f, /var/run/infra/config/config.yaml]
          ports:
{{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
{{- end }}
          env:
            - name: INFRA_LOG_LEVEL
              value: {{ get .Values "log-level" | default "info" }}
          volumeMounts:
            - name: config
              mountPath: /var/run/infra/config
              readOnly: true
            - name: data
              mountPath: /var/run/infra/data
            - name: infra-secret
              mountPath: /var/run/secrets/infrahq.com/infra
              readOnly: true
            - name: engine-secret
              mountPath: /var/run/secrets/infrahq.com/engine
              readOnly: true
          readinessProbe:
            httpGet:
              {{- with first .Values.service.ports }}
              scheme: {{ .name | upper }}
              path: /healthz
              port: {{ .targetPort }}
              {{- end }}
          livenessProbe:
            httpGet:
              {{- with first .Values.service.ports }}
              scheme: {{ .name | upper }}
              path: /healthz
              port: {{ .targetPort }}
              {{- end }}
            periodSeconds: 3
      volumes:
        - name: config
          configMap:
            name: {{ include "infra.fullname" . }}
            optional: true
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "infra.fullname" . }}
        - name: infra-secret
          secret:
            secretName: infra
        - name: engine-secret
          secret:
            secretName: infra-engine
