apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "infra.fullname" . }}
  labels:
{{- include "infra.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
{{- include "infra.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
{{- include "infra.selectorLabels" . | nindent 8 }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
{{- with .Values.pod.annotations }}
  {{- toYaml . | nindent 8 }}
{{- end }}
    spec:
      automountServiceAccountToken: true
      serviceAccountName: {{ include "infra.serviceAccountName" . }}
      dnsPolicy: ClusterFirst
{{- with .Values.image.pullSecrets }}
      imagePullSecrets:
  {{- range . }}
        - name: {{ . }}
  {{- end }}
{{- end }}
      containers:
        - name: infra
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "start"
            - "-c"
            - "/var/run/infra/config/infra.yaml"
            - "--db-file"
            - "/var/run/infra/data/infra.db"
            - "--tls-cache"
            - "/var/run/infra/data/cache"
            - "--enable-telemetry"
            - {{ .Values.telemetry.enabled | quote }}
            - "--enable-crash-reporting"
            - {{ .Values.crashReporting.enabled | quote }}
          env:
            - name: INFRA_SYNC_INTERVAL_SECONDS
              value: "30s"
            - name: INFRA_ROOT_API_KEY
              value: 'file:///var/run/secrets/infrahq.com/infra/root-key'
            - name: INFRA_ENGINE_API_KEY
              value: 'file:///var/run/secrets/infrahq.com/engine/engine-key'
          ports:
{{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
{{- end }}
          volumeMounts:
            - name: config
              mountPath: /var/run/infra/config
            - name: data
              mountPath: /var/run/infra/data
            - name: secret-infra
              mountPath: /var/run/secrets/infrahq.com/infra
              readOnly: true
            - name: secret-engine
              mountPath: /var/run/secrets/infrahq.com/engine
              readOnly: true
          readinessProbe:
            httpGet:
              {{- with first .Values.service.ports }}
              scheme: {{ .name | upper }}
              path: /healthz
              port: {{ .targetPort }}
              {{- end }}
          livenessProbe:
            httpGet:
              {{- with first .Values.service.ports }}
              scheme: {{ .name | upper }}
              path: /healthz
              port: {{ .targetPort }}
              {{- end }}
            periodSeconds: 3
      volumes:
        - name: config
          configMap:
            name: {{ include "infra.fullname" . }}
            optional: true
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "infra.fullname" . }}
        - name: secret-infra
          secret:
            secretName: infra
        - name: secret-engine
          secret:
            secretName: infra-engine
