apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: infra
  replicas: 1
  template:
    metadata:
      labels:
        app: infra
    spec:
      automountServiceAccountToken: true
      containers:
        - name: registry
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["registry", "-c", "/var/run/infra/config/infra.yaml", "--db", "/var/run/infra/data/infra.db", "--tls-cache", "/var/run/infra/data/cache"]
          env:
            - name: INFRA_REGISTRY_DEFAULT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: infra
                  key: defaultApiKey
                  optional: true
          ports:
            - containerPort: 443
          volumeMounts:
            - name: data
              mountPath: /var/run/infra/data
            - name: config
              mountPath: /var/run/infra/config
          livenessProbe:
            httpGet:
              path: /healthz
              scheme: HTTPS
              port: 443
            periodSeconds: 3
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - infra
            topologyKey: kubernetes.io/hostname
      volumes:
        - name: config
          configMap:
            name: infra
            optional: true
        - name: data
          persistentVolumeClaim:
            claimName: infra