{{- define "root.key" }}
{{- $fullname := include "infra.fullname" . }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace "infra" }}
  {{- if $secret }}
    {{- index $secret "data" "root-key" | b64dec }}
  {{- else }}
    {{- randAlphaNum 24 }}
  {{- end }}
{{- end }}
{{- define "engine.key" }}
{{- $fullname := include "infra.fullname" . }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace "infra-engine" }}
  {{- if $secret }}
    {{- index $secret "data" "engine-key" | b64dec }}
  {{- else }}
    {{- randAlphaNum 24 }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: infra
  labels:
{{- include "infra.labels" . | nindent 4 }}
type: Opaque
data:
  root-key: {{ include "root.key" . | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: infra-engine
  labels:
{{- include "infra.labels" . | nindent 4 }}
type: Opaque
data:
  engine-key: {{ include "engine.key" . | b64enc | quote }}
