{{- define "root.apiKey" }}
{{- if get .Values "root-api-key" | hasPrefix "file:" }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace "infra" }}
  {{- if $secret }}
    {{- index $secret "data" "root-api-key" | b64dec }}
  {{- else }}
    {{- randAlphaNum 24 }}
  {{- end }}
{{- else }}
{{- get .Values "root-api-key" }}
{{- end }}
{{- end }}
{{- define "engine.apiKey" }}
{{- if get .Values "engine-api-key" | hasPrefix "file:" }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace "infra-engine" }}
  {{- if $secret }}
    {{- index $secret "data" "engine-api-key" | b64dec }}
  {{- else }}
    {{- randAlphaNum 24 }}
  {{- end }}
{{- else }}
{{- get .Values "engine-api-key" }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: infra
  labels:
{{- include "infra.labels" . | nindent 4 }}
type: Opaque
data:
  root-api-key: {{ include "root.apiKey" . | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: infra-engine
  labels:
{{- include "infra.labels" . | nindent 4 }}
type: Opaque
data:
  engine-api-key: {{ include "engine.apiKey" . | b64enc | quote }}
