{{- if and .Values.engine.enabled (not .Values.engine.config.accessKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-access-key
  labels:
{{- include "infra.labels" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ include "infra.accessKey" . | b64enc | quote }}
{{- end }}
