apiVersion: v1
kind: Secret
metadata:
  name: infra
  labels:
{{- include "infra.labels" . | nindent 4 }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: infra-engine
  labels:
{{- include "infra.labels" . | nindent 4 }}
type: Opaque
