{{- define "infra.systemAccessKey" -}}
{{- if .Values.systemAccessKey }}
{{- .Values.systemAccessKey }}
{{- else }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace "infra" }}
  {{- if $secret }}
    {{- index $secret "data" "system-access-key" | b64dec }}
  {{- else }}
    {{- randAlphaNum 10 }}.{{ randAlphaNum 24 }}
  {{- end }}
{{- end }}
{{- end }}
---
{{- define "infra.engineAccessKey" -}}
{{- if .Values.engineAccessKey }}
{{- .Values.engineAccessKey }}
{{- else }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace "infra-engine" }}
  {{- if $secret }}
    {{- index $secret "data" "access-key" | b64dec }}
  {{- else }}
    {{- randAlphaNum 10 }}.{{ randAlphaNum 24 }}
  {{- end }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: infra
  labels:
{{- include "infra.labels" . | nindent 4 }}
type: Opaque
data:
  system-access-key: {{ include "infra.systemAccessKey" . | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: infra-engine
  labels:
{{- include "infra.labels" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ include "infra.engineAccessKey" . | b64enc | quote }}
