{{- define "root.apiToken" }}
{{- if .Values.rootAPIToken }}
{{- .Values.rootAPIToken }}
{{- else }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace "infra" }}
  {{- if $secret }}
    {{- index $secret "data" "root-api-token" | b64dec }}
  {{- else }}
    {{- randAlphaNum 36 }}
  {{- end }}
{{- end }}
{{- end }}
{{- define "engine.apiToken" }}
{{- if .Values.engineAPIToken }}
{{- .Values.engineAPIToken }}
{{- else }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace "infra-engine" }}
  {{- if $secret }}
    {{- index $secret "data" "engine-api-token" | b64dec }}
  {{- else }}
    {{- randAlphaNum 36 }}
  {{- end }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: infra
  labels:
{{- include "infra.labels" . | nindent 4 }}
type: Opaque
data:
  root-api-token: {{ include "root.apiToken" . | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: infra-engine
  labels:
{{- include "infra.labels" . | nindent 4 }}
type: Opaque
data:
  engine-api-token: {{ include "engine.apiToken" . | b64enc | quote }}
