name: ""
registry: ""
apiKey: ""

image:
  repository: infrahq/infra
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  labels: {}
  annotations: {}
  ports:
    - name: https
      port: 443
      targetPort: 443

ingress:
  enabled: false
  labels: {}
  annotations: {}
  servicePort: 443
  hosts: []
  tls: []
