name: ""
host: ""
apiKey: ""
tlsCache: /var/run/infra/data/cache
skipTLSVerify: true
labels: []

storage: 1Gi

pod:
  annotations: {}

serviceAccount:
  create: true
  annotations: {}

image:
  repository: infrahq/infra
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  labels: {}
  annotations: {}
  ports:
    - name: https
      port: 443
      targetPort: 443
