/* tslint:disable */
/* eslint-disable */
/**
 * Infra API
 * Infra REST API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Machine,
    MachineFromJSON,
    MachineToJSON,
    MachineAPIKey,
    MachineAPIKeyFromJSON,
    MachineAPIKeyToJSON,
    MachineAPIKeyCreateRequest,
    MachineAPIKeyCreateRequestFromJSON,
    MachineAPIKeyCreateRequestToJSON,
} from '../models';

export interface CreateMachineAPIKeyRequest {
    body: MachineAPIKeyCreateRequest;
}

export interface DeleteMachineRequest {
    id: string;
}

export interface ListMachinesRequest {
    name?: string;
}

/**
 * 
 */
export class MachinesApi extends runtime.BaseAPI {

    /**
     * Register a machine API key
     */
    async createMachineAPIKeyRaw(requestParameters: CreateMachineAPIKeyRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<MachineAPIKey>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling createMachineAPIKey.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/machines/apiKeys`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MachineAPIKeyCreateRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MachineAPIKeyFromJSON(jsonValue));
    }

    /**
     * Register a machine API key
     */
    async createMachineAPIKey(requestParameters: CreateMachineAPIKeyRequest, initOverrides?: RequestInit): Promise<MachineAPIKey> {
        const response = await this.createMachineAPIKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * delete a machine
     */
    async deleteMachineRaw(requestParameters: DeleteMachineRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteMachine.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/machines/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete a machine
     */
    async deleteMachine(requestParameters: DeleteMachineRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deleteMachineRaw(requestParameters, initOverrides);
    }

    /**
     * List machines
     */
    async listMachinesRaw(requestParameters: ListMachinesRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Machine>>> {
        const queryParameters: any = {};

        if (requestParameters.name !== undefined) {
            queryParameters['name'] = requestParameters.name;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/machines`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MachineFromJSON));
    }

    /**
     * List machines
     */
    async listMachines(requestParameters: ListMachinesRequest, initOverrides?: RequestInit): Promise<Array<Machine>> {
        const response = await this.listMachinesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
