---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "engine.fullname" . }}
  labels:
{{- include "engine.labels" . | nindent 4 }}
data:
  config.yaml: |
{{- $options := list "name" "host" "api-key" }}
{{- $options = list "tls-cache" "skip-tls-verify" | concat $options }}
{{- range $options }}
  {{- if hasKey $.Values . }}
    {{ . }}: {{ get $.Values . }}
  {{- end }}
{{- end }}
