---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "engine.fullname" . }}
  labels:
{{- include "engine.labels" . | nindent 4 }}
data:
  config.yaml: |
    kind: kubernetes
    api-key: file:///var/run/secrets/infrahq.com/engine/engine-api-key
{{- $options := list "name" "host" }}
{{- $options = list "tlsCache" "skipTLSVerify" | concat $options }}
{{- $options = list "labels" | concat $options }}
{{- range $options }}
  {{- if hasKey $.Values . }}
    {{- if get $.Values . | kindIs "slice" }}
    {{ . | kebabcase }}:
    {{- range get $.Values . }}
      - {{ . }}
    {{- end }}
    {{- else }}
    {{ . | kebabcase }}: {{ get $.Values . }}
    {{- end }}
  {{- end }}
{{- end }}
