{{- $config := omit .Values.config "accessKey" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "engine.fullname" . }}
  labels:
{{- include "engine.labels" . | nindent 4 }}
data:
  config.yaml: |-
    accessKey: /var/run/secrets/infrahq.com/engine/access-key
    {{- toYaml $config | nindent 4 }}
