{{- $config := omit .Values.config "apiToken" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "engine.fullname" . }}
  labels:
{{- include "engine.labels" . | nindent 4 }}
data:
  config.yaml: |-
    apiToken: file:///var/run/secrets/infrahq.com/engine/engine-api-token
    {{- toYaml $config | nindent 4 }}
