apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-engine
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: infra-engine
  replicas: 1
  template:
    metadata:
      labels:
        app: infra-engine
    spec:
      automountServiceAccountToken: true
      serviceAccountName: infra-engine
      containers:
        - name: engine
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["engine"]
          ports:
            - containerPort: 80
          env:
            {{- if .Values.name }}
            - name: INFRA_ENGINE_NAME
              value: {{ .Values.name | quote }}
            {{- end }}
            {{- if .Values.endpoint }}
            - name: INFRA_ENGINE_ENDPOINT
              value: {{ .Values.endpoint | quote }}
            {{- end }}
            - name: INFRA_ENGINE_REGISTRY
              value: {{ required "Value registry is required" .Values.registry | quote }}
            - name: INFRA_LOG_LEVEL
              value: info
            - name: INFRA_ENGINE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: infra-engine
                  key: api-key
                  optional: true
          volumeMounts:
            - name: infra-engine-anonymous
              mountPath: "/var/run/secrets/infra-engine-anonymous"
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 3
      volumes:
        - name: infra-engine-anonymous
          secret:
            secretName: infra-engine-anonymous-secret