apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "engine.fullname" . }}
  labels:
{{- include "engine.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
{{- include "engine.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
{{- include "engine.selectorLabels" . | nindent 8 }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
{{- with .Values.pod.annotations }}
  {{- toYaml . | nindent 8 }}
{{- end }}
    spec:
      automountServiceAccountToken: true
      serviceAccountName: {{ include "engine.serviceAccountName" . }}
      dnsPolicy: ClusterFirst
{{- with .Values.image.pullSecrets }}
      imagePullSecrets:
  {{- range . }}
        - name: {{ . }}
  {{- end }}
{{- end }}
      containers:
        - name: engine
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["engine", "-f", "/var/run/infra/config/config.yaml", "--log-level", {{ .Values.logLevel | quote }}]
          ports:
{{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
{{- end }}
          env:
            - name: INFRA_V
              value: {{ .Values.v | quote }}
          volumeMounts:
            - name: config
              mountPath: /var/run/infra/config
              readOnly: true
            - name: data
              mountPath: /var/run/infra/data
            - name: engine-secret
              mountPath: /var/run/secrets/infrahq.com/engine
              readOnly: true
          readinessProbe:
            httpGet:
{{- with first .Values.service.ports }}
              scheme: {{ .name | upper }}
              path: /healthz
              port: {{ .targetPort }}
{{- end }}
          livenessProbe:
            httpGet:
{{- with first .Values.service.ports }}
              scheme: {{ .name | upper }}
              path: /healthz
              port: {{ .targetPort }}
{{- end }}
            periodSeconds: 3
      volumes:
        - name: config
          configMap:
            name: {{ include "engine.fullname" . }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "engine.fullname" . }}
        - name: engine-secret
          secret:
            secretName: infra-engine
