apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: infra-engine-service
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["services/proxy"]
    resourceNames: ["http:infra-engine:80"]
    verbs: ["*"]
