apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infra-engine-service
  namespace: {{ .Release.Namespace }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:anonymous
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: infra-engine-service