apiVersion: v1
kind: Secret
metadata:
  name: {{ include "engine.fullname" . }}
  labels:
{{- include "engine.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.apiKey | b64enc | quote }}
