{{- if .Values.apiKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: infra-engine
  labels:
{{- include "engine.labels" . | nindent 4 }}
type: Opaque
data:
  engine-key: {{ .Values.apiKey | b64enc | quote }}
{{- end }}
