{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "engine.fullname" . }}
  labels:
{{- include "engine.labels" . | nindent 4 }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
