apiVersion: v1
kind: Service
metadata:
  name: infra-engine
  namespace: {{ .Release.Namespace }}
  labels:
    app: infra-engine
spec:
  type: ClusterIP
  selector:
    app: infra-engine
  ports:
    - name: https
      port: 443
      targetPort: 443
