
ARG image_tag=ubuntu:22.10
FROM $image_tag

ENV DEBIAN_FRONTEND noninteractive

RUN set -eux \
    && apt-get update \
    && apt-get install --no-install-recommends -y \
      bash \
      systemd \
      systemd-sysv \
    # clean systemd \
    && rm -rf /etc/systemd/system/*.wants/* \
      /lib/systemd/system/local-fs.target.wants/* \
      /lib/systemd/system/multi-user.target.wants/* \
      /lib/systemd/system/sockets.target.wants/*initctl* \
      /lib/systemd/system/sockets.target.wants/*udev* \
      /lib/systemd/system/sysinit.target.wants/systemd-tmpfiles-setup* \
      /lib/systemd/system/systemd-update-utmp*

CMD ["/lib/systemd/systemd"]
