apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "engine.fullname" . }}
  labels:
{{- include "engine.labels" . | nindent 4 }}
data:
  infra.yaml: |
{{- if and .Values.global (not (hasKey .Values.config "server")) }}
    server: {{ .Release.Name }}-server.{{ .Release.Namespace }}
{{- end }}

{{- range $key, $val := .Values.config }}
{{- if kindIs "invalid" $val }}
    # skipping invalid value: {{ $val }} ({{ kindOf $val }})
{{- else if kindIs "map" $val }}
    {{ $key }}:
{{- $val | toYaml | nindent 6 }}
{{- else if kindIs "slice" $val }}
    {{ $key }}:
{{- $val | toYaml | nindent 6 }}
{{- else if kindIs "string" $val }}
    {{ $key }}: {{ tpl $val $ }}
{{- else }}
    {{ $key }}: {{ $val }}
{{- end }}
{{- end }}
