apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "engine.fullname" . }}
  labels:
{{- include "engine.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
{{- include "engine.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{- include "engine.podLabels" . | nindent 8 }}
      annotations:
{{- include "engine.podAnnotations" . | nindent 8 }}
    spec:
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      serviceAccountName: {{ include "engine.serviceAccountName" . }}
      imagePullSecrets:
{{- include "engine.imagePullSecrets" . | nindent 8 }}
      securityContext:
{{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
{{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ include "engine.image.repository" . }}:{{ include "engine.image.tag" . }}"
          imagePullPolicy: {{ include "engine.image.pullPolicy" . }}
          args: ["engine", "-f", "/etc/infrahq/infra.yaml"]
          env:
{{- toYaml .Values.env | nindent 12 }}
          envFrom:
{{- toYaml .Values.envFrom | nindent 12 }}
          volumeMounts:
            - name: conf
              mountPath: /etc/infrahq
              readOnly: true
{{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /var/lib/infrahq/infra
{{- end }}
            - name: access-key
              mountPath: /var/run/secrets/infrahq.com/access-key
{{- if .Values.volumeMounts }}
{{- toYaml .Values.volumeMounts | nindent 12 }}
{{- end }}
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: conf
          configMap:
            name: {{ include "engine.fullname" . }}
{{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "engine.fullname" . }}
{{- end }}
        - name: access-key
          secret:
            secretName: {{ .Release.Name }}-access-key
            optional: true
{{- if .Values.volumes }}
{{- toYaml .Values.volumes | nindent 8 }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
