name: ci/commit

on:
  pull_request:

jobs:
  commit-lint:
    if: ${{ ! startsWith(github.head_ref, 'dependabot/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
      - run: npm install -g @commitlint/{config-conventional,cli}
      - run: npx @commitlint/cli --from origin/$GITHUB_BASE_REF --to @ --verbose --config .github/commitlint.config.js
