/*
 * Infra API
 *
 * Infra REST API
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
	"errors"
	"net/http"
)

// GroupsApiService is a service that implents the logic for the GroupsApiServicer
// This service should implement the business logic for every endpoint for the GroupsApi API.
// Include any external packages or services that will be required by this service.
type GroupsApiService struct {
}

// NewGroupsApiService creates a default api service
func NewGroupsApiService() GroupsApiServicer {
	return &GroupsApiService{}
}

// ListGroups - List groups
func (s *GroupsApiService) ListGroups(ctx context.Context) (ImplResponse, error) {
	// TODO - update ListGroups with the required logic for this service method.
	// Add api_groups_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []Group{}) or use other options such as http.Ok ...
	//return Response(200, []Group{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListGroups method not implemented")
}
