/*
 * Infra API
 *
 * Infra REST API
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
	"errors"
	"net/http"
)

// DestinationsApiService is a service that implents the logic for the DestinationsApiServicer
// This service should implement the business logic for every endpoint for the DestinationsApi API.
// Include any external packages or services that will be required by this service.
type DestinationsApiService struct {
}

// NewDestinationsApiService creates a default api service
func NewDestinationsApiService() DestinationsApiServicer {
	return &DestinationsApiService{}
}

// CreateDestination - Register a destination
func (s *DestinationsApiService) CreateDestination(ctx context.Context, body DestinationCreateRequest) (ImplResponse, error) {
	// TODO - update CreateDestination with the required logic for this service method.
	// Add api_destinations_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Destination{}) or use other options such as http.Ok ...
	//return Response(200, Destination{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateDestination method not implemented")
}

// ListDestinations - List destinations
func (s *DestinationsApiService) ListDestinations(ctx context.Context) (ImplResponse, error) {
	// TODO - update ListDestinations with the required logic for this service method.
	// Add api_destinations_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []Destination{}) or use other options such as http.Ok ...
	//return Response(200, []Destination{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListDestinations method not implemented")
}
