/*
 * Infra API
 *
 * Infra REST API
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
	"errors"
	"net/http"
)

// RolesApiService is a service that implents the logic for the RolesApiServicer
// This service should implement the business logic for every endpoint for the RolesApi API.
// Include any external packages or services that will be required by this service.
type RolesApiService struct {
}

// NewRolesApiService creates a default api service
func NewRolesApiService() RolesApiServicer {
	return &RolesApiService{}
}

// ListRoles - List roles
func (s *RolesApiService) ListRoles(ctx context.Context, destinationId string) (ImplResponse, error) {
	// TODO - update ListRoles with the required logic for this service method.
	// Add api_roles_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []Role{}) or use other options such as http.Ok ...
	//return Response(200, []Role{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListRoles method not implemented")
}
