/*
 * Infra API
 *
 * Infra REST API
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// SourcesApiController binds http requests to an api service and writes the service results to the http response
type SourcesApiController struct {
	service      SourcesApiServicer
	errorHandler ErrorHandler
}

// SourcesApiOption for how the controller is set up.
type SourcesApiOption func(*SourcesApiController)

// WithSourcesApiErrorHandler inject ErrorHandler into controller
func WithSourcesApiErrorHandler(h ErrorHandler) SourcesApiOption {
	return func(c *SourcesApiController) {
		c.errorHandler = h
	}
}

// NewSourcesApiController creates a default api controller
func NewSourcesApiController(s SourcesApiServicer, opts ...SourcesApiOption) Router {
	controller := &SourcesApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all of the api route for the SourcesApiController
func (c *SourcesApiController) Routes() Routes {
	return Routes{
		{
			"ListSources",
			strings.ToUpper("Get"),
			"/sources",
			c.ListSources,
		},
	}
}

// ListSources - List sources
func (c *SourcesApiController) ListSources(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.ListSources(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}
