/*
 * Infra API
 *
 * Infra REST API
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type AuthResponse struct {
	Token string `json:"token"`
}

// AssertAuthResponseRequired checks if the required fields are not zero-ed
func AssertAuthResponseRequired(obj AuthResponse) error {
	elements := map[string]interface{}{
		"token": obj.Token,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseAuthResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AuthResponse (e.g. [][]AuthResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAuthResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAuthResponse, ok := obj.(AuthResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAuthResponseRequired(aAuthResponse)
	})
}
