/*
 * Infra API
 *
 * Infra REST API
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type LoginRequestInfra struct {
	Email string `json:"email"`

	Password string `json:"password"`
}

// AssertLoginRequestInfraRequired checks if the required fields are not zero-ed
func AssertLoginRequestInfraRequired(obj LoginRequestInfra) error {
	elements := map[string]interface{}{
		"email":    obj.Email,
		"password": obj.Password,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseLoginRequestInfraRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of LoginRequestInfra (e.g. [][]LoginRequestInfra), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseLoginRequestInfraRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aLoginRequestInfra, ok := obj.(LoginRequestInfra)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertLoginRequestInfraRequired(aLoginRequestInfra)
	})
}
