/*
 * Infra API
 *
 * Infra REST API
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type SignupRequest struct {
	Email string `json:"email"`

	Password string `json:"password"`
}

// AssertSignupRequestRequired checks if the required fields are not zero-ed
func AssertSignupRequestRequired(obj SignupRequest) error {
	elements := map[string]interface{}{
		"email":    obj.Email,
		"password": obj.Password,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseSignupRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SignupRequest (e.g. [][]SignupRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSignupRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSignupRequest, ok := obj.(SignupRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSignupRequestRequired(aSignupRequest)
	})
}
