/*
 * Infra API
 *
 * Infra REST API
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type Source struct {
	Id string `json:"id"`

	Created int64 `json:"created"`

	Updated int64 `json:"updated"`

	Okta SourceOkta `json:"okta,omitempty"`
}

// AssertSourceRequired checks if the required fields are not zero-ed
func AssertSourceRequired(obj Source) error {
	elements := map[string]interface{}{
		"id":      obj.Id,
		"created": obj.Created,
		"updated": obj.Updated,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertSourceOktaRequired(obj.Okta); err != nil {
		return err
	}
	return nil
}

// AssertRecurseSourceRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Source (e.g. [][]Source), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSourceRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSource, ok := obj.(Source)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSourceRequired(aSource)
	})
}
