apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "registry.fullname" . }}
  labels:
{{- include "registry.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
{{- include "registry.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
{{- include "registry.selectorLabels" . | nindent 8 }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
{{- with .Values.pod.annotations }}
  {{- toYaml . | nindent 8 }}
{{- end }}
    spec:
      automountServiceAccountToken: true
      serviceAccountName: {{ include "registry.serviceAccountName" . }}
      dnsPolicy: ClusterFirst
{{- with .Values.image.pullSecrets }}
      imagePullSecrets:
  {{- range . }}
        - name: {{ . }}
  {{- end }}
{{- end }}
      containers:
        - name: registry
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "registry"
            - "-c"
            - "/var/run/infra/config/infra.yaml"
            - "--db"
            - "/var/run/infra/data/infra.db"
            - "--tls-cache"
            - "/var/run/infra/data/cache"
            - "--enable-telemetry"
            - {{ .Values.telemetry.enabled | quote }}
            - "--enable-crash-reporting"
            - {{ .Values.crashReporting.enabled | quote }}
          env:
            - name: INFRA_LOG_LEVEL
              value: {{ .Values.logLevel | default "info" }}
            - name: INFRA_SYNC_INTERVAL_SECONDS
              value: "30"
            - name: INFRA_ROOT_SECRET
              value: 'file:///var/run/secrets/infrahq.com/registry/root-key'
            - name: INFRA_ENGINE_SECRET
              value: 'file:///var/run/secrets/infrahq.com/engine/engine-key'
          ports:
{{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
{{- end }}
          volumeMounts:
            - name: config
              mountPath: /var/run/infra/config
            - name: data
              mountPath: /var/run/infra/data
            - name: secret-registry
              mountPath: /var/run/secrets/infrahq.com/registry
              readOnly: true
            - name: secret-engine
              mountPath: /var/run/secrets/infrahq.com/engine
              readOnly: true
          readinessProbe:
            httpGet:
              {{- with first .Values.service.ports }}
              scheme: {{ .name | upper }}
              path: /healthz
              port: {{ .targetPort }}
              {{- end }}
          livenessProbe:
            httpGet:
              {{- with first .Values.service.ports }}
              scheme: {{ .name | upper }}
              path: /healthz
              port: {{ .targetPort }}
              {{- end }}
            periodSeconds: 3
      volumes:
        - name: config
          configMap:
            name: infra-registry
            optional: true
        - name: data
          persistentVolumeClaim:
            claimName: infra-registry
        - name: secret-registry
          secret:
            secretName: infra-registry
        - name: secret-engine
          secret:
            secretName: infra-engine
