apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra
  namespace: infra
spec:
  selector:
    matchLabels:
      app: infra
  replicas: 1
  template:
    metadata:
      labels:
        app: infra
    spec:
      automountServiceAccountToken: true
      containers:
        - name: registry
          image: infrahq/infra:{{ .Chart.AppVersion }}
          args: ["registry", "-c", "/var/run/infra/config/infra.yaml", "--db", "/var/run/infra/data/infra.db", "--tls-cache", "/var/run/infra/data/cache"]
          ports:
            - containerPort: 443
          volumeMounts:
            - name: data
              mountPath: /var/run/infra/data
            - name: config
              mountPath: /var/run/infra/config
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 3
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - infra
            topologyKey: kubernetes.io/hostname
      volumes:
        - name: config
          configMap:
            name: infra
            optional: true
        - name: data
          persistentVolumeClaim:
            claimName: infra
