{{- define "ingress.apiVersion" }}
{{- $kubeVersion := default .Capabilities.KubeVersion.Version .Values.kubeVersionOverride }}
{{- if semverCompare "<1.19-0" $kubeVersion }}
{{- print "networking.k8s.io/v1beta1" }}
{{- else }}
{{- print "networking.k8s.io/v1" }}
{{- end }}
{{- end }}
{{- if .Values.ingress.enabled -}}
{{- $apiVersion := include "ingress.apiVersion" $ }}
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: infra-registry
  namespace: {{ .Release.Namespace }}
  labels:
    app: infra-registry
{{- with .Values.ingress.labels }}
  {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  rules:
{{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
  {{- if eq $apiVersion "networking.k8s.io/v1" }}
            pathType: Prefix
  {{- end }}
            backend:
  {{- if eq $apiVersion "networking.k8s.io/v1" }}
              service:
                name: infra-registry
                port:
                  number: {{ $.Values.ingress.servicePort }}
  {{- else }}
              serviceName: infra-registry
              servicePort: {{ $.Values.ingress.servicePort }}
  {{- end }}
{{- end -}}
{{- with .Values.ingress.tls }}
  tls:
  {{- range . }}
    - hosts:
    {{- range .hosts }}
      - {{ . }}
    {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
{{- end }}
