apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infra
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage }}
