apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infra-pod-secret-access
  namespace: {{ .Release.Namespace }}
subjects:
- kind: User
  name: system:serviceaccount:{{ .Release.Namespace }}:default
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: infra-pod-secret-access