apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "registry.fullname" . }}
  labels:
{{- include "registry.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
