apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: infra-registry-secret-reader
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
