{{- define "rootApiKey" }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace "infra-registry" }}
  {{- if $secret }}
    {{- index $secret "data" "rootApiKey" | b64dec }}
  {{- else }}
    {{- randAlphaNum 24 }}
  {{- end }}
{{- end }}
{{- define "engineApiKey" }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace "infra-registry" }}
  {{- if $secret }}
    {{- index $secret "data" "engineApiKey" | b64dec }}
  {{- else }}
    {{- randAlphaNum 24 }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry.fullname" . }}
  labels:
{{- include "registry.labels" . | nindent 4 }}
type: Opaque
data:
  rootApiKey: {{ include "rootApiKey" . | b64enc | quote }}
{{- if .Values.engineApiKey }}
  engineApiKey: {{ .Values.engineApiKey | b64enc | quote }}
{{- else }}
  engineApiKey: {{ include "engineApiKey" . | b64enc | quote }}
{{- end }}
