{{- define "defaultApiKey" }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace "infra-registry" }}
  {{- if $secret }}
    {{- index $secret "data" "defaultApiKey" | b64dec }}
  {{- else }}
    {{- randAlphaNum 24 }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: infra-registry
  namespace: {{ .Release.Namespace }}
  labels:
type: Opaque
data:
{{- if .Values.defaultApiKey }}
  defaultApiKey: {{ .Values.defaultApiKey | b64enc | quote }}
{{- else }}
  defaultApiKey: {{ include "defaultApiKey" . | b64enc | quote }}
{{- end }}
