/* tslint:disable */
/* eslint-disable */
/**
 * Infra API
 * Infra REST API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * API permissions of the form "infra.resource.action"
 * @export
 * @enum {string}
 */
export enum APIPermission {
    UsersRead = 'infra.users.read',
    GroupsRead = 'infra.groups.read',
    DestinationsCreate = 'infra.destinations.create',
    DestinationsRead = 'infra.destinations.read',
    ApiKeysCreate = 'infra.api-keys.create',
    ApiKeysRead = 'infra.api-keys.read',
    ApiKeysDelete = 'infra.api-keys.delete',
    CredsCreate = 'infra.creds.create',
    RolesRead = 'infra.roles.read',
    AuthDelete = 'infra.auth.delete',
    Star = 'infra.*'
}

export function APIPermissionFromJSON(json: any): APIPermission {
    return APIPermissionFromJSONTyped(json, false);
}

export function APIPermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIPermission {
    return json as APIPermission;
}

export function APIPermissionToJSON(value?: APIPermission | null): any {
    return value as any;
}

