/* tslint:disable */
/* eslint-disable */
/**
 * Infra API
 * Infra REST API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Service,
    ServiceFromJSON,
    ServiceFromJSONTyped,
    ServiceToJSON,
    ServiceKind,
    ServiceKindFromJSON,
    ServiceKindFromJSONTyped,
    ServiceKindToJSON,
} from './';

/**
 * 
 * @export
 * @interface ApiService
 */
export interface ApiService {
    /**
     * 
     * @type {string}
     * @memberof ApiService
     */
    apiToken: string;
    /**
     * 
     * @type {string}
     * @memberof ApiService
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof ApiService
     */
    created: number;
    /**
     * 
     * @type {string}
     * @memberof ApiService
     */
    name: string;
    /**
     * 
     * @type {ServiceKind}
     * @memberof ApiService
     */
    kind?: ServiceKind;
}

export function ApiServiceFromJSON(json: any): ApiService {
    return ApiServiceFromJSONTyped(json, false);
}

export function ApiServiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiService {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apiToken': json['apiToken'],
        'id': json['id'],
        'created': json['created'],
        'name': json['name'],
        'kind': !exists(json, 'kind') ? undefined : ServiceKindFromJSON(json['kind']),
    };
}

export function ApiServiceToJSON(value?: ApiService | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apiToken': value.apiToken,
        'id': value.id,
        'created': value.created,
        'name': value.name,
        'kind': ServiceKindToJSON(value.kind),
    };
}


