/* tslint:disable */
/* eslint-disable */
/**
 * Infra API
 * Infra REST API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Cred
 */
export interface Cred {
    /**
     * 
     * @type {string}
     * @memberof Cred
     */
    token: string;
    /**
     * 
     * @type {number}
     * @memberof Cred
     */
    expires: number;
}

export function CredFromJSON(json: any): Cred {
    return CredFromJSONTyped(json, false);
}

export function CredFromJSONTyped(json: any, ignoreDiscriminator: boolean): Cred {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
        'expires': json['expires'],
    };
}

export function CredToJSON(value?: Cred | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
        'expires': value.expires,
    };
}


