/* tslint:disable */
/* eslint-disable */
/**
 * Infra API
 * Infra REST API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DestinationKubernetes
 */
export interface DestinationKubernetes {
    /**
     * 
     * @type {string}
     * @memberof DestinationKubernetes
     */
    ca: string;
    /**
     * 
     * @type {string}
     * @memberof DestinationKubernetes
     */
    endpoint: string;
    /**
     * 
     * @type {string}
     * @memberof DestinationKubernetes
     */
    namespace: string;
    /**
     * 
     * @type {string}
     * @memberof DestinationKubernetes
     */
    saToken: string;
}

export function DestinationKubernetesFromJSON(json: any): DestinationKubernetes {
    return DestinationKubernetesFromJSONTyped(json, false);
}

export function DestinationKubernetesFromJSONTyped(json: any, ignoreDiscriminator: boolean): DestinationKubernetes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ca': json['ca'],
        'endpoint': json['endpoint'],
        'namespace': json['namespace'],
        'saToken': json['saToken'],
    };
}

export function DestinationKubernetesToJSON(value?: DestinationKubernetes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ca': value.ca,
        'endpoint': value.endpoint,
        'namespace': value.namespace,
        'saToken': value.saToken,
    };
}


