/* tslint:disable */
/* eslint-disable */
/**
 * Infra API
 * Infra REST API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum DestinationKind {
    Kubernetes = 'kubernetes'
}

export function DestinationKindFromJSON(json: any): DestinationKind {
    return DestinationKindFromJSONTyped(json, false);
}

export function DestinationKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): DestinationKind {
    return json as DestinationKind;
}

export function DestinationKindToJSON(value?: DestinationKind | null): any {
    return value as any;
}

