/**
 * Infra API
 * Infra REST API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DestinationKubernetes } from './DestinationKubernetes';
import { HttpFile } from '../http/http';

export class DestinationCreateRequest {
    'name': string;
    'kubernetes'?: DestinationKubernetes;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "kubernetes",
            "baseName": "kubernetes",
            "type": "DestinationKubernetes",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DestinationCreateRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}

