/* tslint:disable */
/* eslint-disable */
/**
 * Infra API
 * Infra REST API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GrantResource
 */
export interface GrantResource {
    /**
     * 
     * @type {string}
     * @memberof GrantResource
     */
    kind: string;
    /**
     * 
     * @type {string}
     * @memberof GrantResource
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GrantResource
     */
    path: string;
}

export function GrantResourceFromJSON(json: any): GrantResource {
    return GrantResourceFromJSONTyped(json, false);
}

export function GrantResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrantResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'name': json['name'],
        'path': json['path'],
    };
}

export function GrantResourceToJSON(value?: GrantResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'kind': value.kind,
        'name': value.name,
        'path': value.path,
    };
}


