/* tslint:disable */
/* eslint-disable */
/**
 * Infra API
 * Infra REST API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GrantResource,
    GrantResourceFromJSON,
    GrantResourceFromJSONTyped,
    GrantResourceToJSON,
} from './';

/**
 * 
 * @export
 * @interface GrantRequest
 */
export interface GrantRequest {
    /**
     * 
     * @type {string}
     * @memberof GrantRequest
     */
    role: string;
    /**
     * 
     * @type {GrantResource}
     * @memberof GrantRequest
     */
    resource: GrantResource;
    /**
     * 
     * @type {Array<string>}
     * @memberof GrantRequest
     */
    users?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GrantRequest
     */
    groups?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GrantRequest
     */
    labels?: Array<string>;
}

export function GrantRequestFromJSON(json: any): GrantRequest {
    return GrantRequestFromJSONTyped(json, false);
}

export function GrantRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrantRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'role': json['role'],
        'resource': GrantResourceFromJSON(json['resource']),
        'users': !exists(json, 'users') ? undefined : json['users'],
        'groups': !exists(json, 'groups') ? undefined : json['groups'],
        'labels': !exists(json, 'labels') ? undefined : json['labels'],
    };
}

export function GrantRequestToJSON(value?: GrantRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'role': value.role,
        'resource': GrantResourceToJSON(value.resource),
        'users': value.users,
        'groups': value.groups,
        'labels': value.labels,
    };
}


