/* tslint:disable */
/* eslint-disable */
/**
 * Infra API
 * Infra REST API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InfraAPIKey
 */
export interface InfraAPIKey {
    /**
     * 
     * @type {string}
     * @memberof InfraAPIKey
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof InfraAPIKey
     */
    created: number;
    /**
     * 
     * @type {string}
     * @memberof InfraAPIKey
     */
    name: string;
}

export function InfraAPIKeyFromJSON(json: any): InfraAPIKey {
    return InfraAPIKeyFromJSONTyped(json, false);
}

export function InfraAPIKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): InfraAPIKey {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'created': json['created'],
        'name': json['name'],
    };
}

export function InfraAPIKeyToJSON(value?: InfraAPIKey | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'created': value.created,
        'name': value.name,
    };
}


