/* tslint:disable */
/* eslint-disable */
/**
 * Infra API
 * Infra REST API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InfraAPIKey,
    InfraAPIKeyFromJSON,
    InfraAPIKeyFromJSONTyped,
    InfraAPIKeyToJSON,
} from './';

/**
 * 
 * @export
 * @interface InfraAPIKeyCreateResponse
 */
export interface InfraAPIKeyCreateResponse {
    /**
     * 
     * @type {string}
     * @memberof InfraAPIKeyCreateResponse
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof InfraAPIKeyCreateResponse
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof InfraAPIKeyCreateResponse
     */
    created: number;
    /**
     * 
     * @type {string}
     * @memberof InfraAPIKeyCreateResponse
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof InfraAPIKeyCreateResponse
     */
    permissions: Array<string>;
}

export function InfraAPIKeyCreateResponseFromJSON(json: any): InfraAPIKeyCreateResponse {
    return InfraAPIKeyCreateResponseFromJSONTyped(json, false);
}

export function InfraAPIKeyCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InfraAPIKeyCreateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'id': json['id'],
        'created': json['created'],
        'name': json['name'],
        'permissions': json['permissions'],
    };
}

export function InfraAPIKeyCreateResponseToJSON(value?: InfraAPIKeyCreateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'id': value.id,
        'created': value.created,
        'name': value.name,
        'permissions': value.permissions,
    };
}


