/* tslint:disable */
/* eslint-disable */
/**
 * Infra API
 * Infra REST API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InfraAPITokenCreateRequest
 */
export interface InfraAPITokenCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof InfraAPITokenCreateRequest
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof InfraAPITokenCreateRequest
     */
    permissions: Array<string>;
    /**
     * token time to live before expirry in the form XhYmZs, for example 1h30m
     * @type {string}
     * @memberof InfraAPITokenCreateRequest
     */
    ttl?: string;
}

export function InfraAPITokenCreateRequestFromJSON(json: any): InfraAPITokenCreateRequest {
    return InfraAPITokenCreateRequestFromJSONTyped(json, false);
}

export function InfraAPITokenCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InfraAPITokenCreateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'permissions': json['permissions'],
        'ttl': !exists(json, 'ttl') ? undefined : json['ttl'],
    };
}

export function InfraAPITokenCreateRequestToJSON(value?: InfraAPITokenCreateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'permissions': value.permissions,
        'ttl': value.ttl,
    };
}


