/* tslint:disable */
/* eslint-disable */
/**
 * Infra API
 * Infra REST API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InfraAPIToken
 */
export interface InfraAPIToken {
    /**
     * 
     * @type {string}
     * @memberof InfraAPIToken
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof InfraAPIToken
     */
    created: number;
    /**
     * 
     * @type {string}
     * @memberof InfraAPIToken
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof InfraAPIToken
     */
    permissions: Array<string>;
    /**
     * token time to live before expiry in the form XhYmZs, for example 1h30m
     * @type {string}
     * @memberof InfraAPIToken
     */
    ttl?: string;
}

export function InfraAPITokenFromJSON(json: any): InfraAPIToken {
    return InfraAPITokenFromJSONTyped(json, false);
}

export function InfraAPITokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): InfraAPIToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'created': json['created'],
        'name': json['name'],
        'permissions': json['permissions'],
        'ttl': !exists(json, 'ttl') ? undefined : json['ttl'],
    };
}

export function InfraAPITokenToJSON(value?: InfraAPIToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'created': value.created,
        'name': value.name,
        'permissions': value.permissions,
        'ttl': value.ttl,
    };
}


