/**
 * Infra API
 * Infra REST API
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LoginRequestInfra } from './LoginRequestInfra';
import { LoginRequestOkta } from './LoginRequestOkta';
import { HttpFile } from '../http/http';

export class LoginRequest {
    'infra'?: LoginRequestInfra;
    'okta'?: LoginRequestOkta;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "infra",
            "baseName": "infra",
            "type": "LoginRequestInfra",
            "format": ""
        },
        {
            "name": "okta",
            "baseName": "okta",
            "type": "LoginRequestOkta",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LoginRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}

