/* tslint:disable */
/* eslint-disable */
/**
 * Infra API
 * Infra REST API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginRequestInfra
 */
export interface LoginRequestInfra {
    /**
     * 
     * @type {string}
     * @memberof LoginRequestInfra
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof LoginRequestInfra
     */
    password: string;
}

export function LoginRequestInfraFromJSON(json: any): LoginRequestInfra {
    return LoginRequestInfraFromJSONTyped(json, false);
}

export function LoginRequestInfraFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginRequestInfra {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function LoginRequestInfraToJSON(value?: LoginRequestInfra | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
    };
}


