/* tslint:disable */
/* eslint-disable */
/**
 * Infra API
 * Infra REST API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Machine,
    MachineFromJSON,
    MachineFromJSONTyped,
    MachineToJSON,
    MachineKind,
    MachineKindFromJSON,
    MachineKindFromJSONTyped,
    MachineKindToJSON,
} from './';

/**
 * 
 * @export
 * @interface MachineAPIKey
 */
export interface MachineAPIKey {
    /**
     * 
     * @type {string}
     * @memberof MachineAPIKey
     */
    apiKey: string;
    /**
     * 
     * @type {string}
     * @memberof MachineAPIKey
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof MachineAPIKey
     */
    created: number;
    /**
     * 
     * @type {string}
     * @memberof MachineAPIKey
     */
    name: string;
    /**
     * 
     * @type {MachineKind}
     * @memberof MachineAPIKey
     */
    kind: MachineKind;
}

export function MachineAPIKeyFromJSON(json: any): MachineAPIKey {
    return MachineAPIKeyFromJSONTyped(json, false);
}

export function MachineAPIKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): MachineAPIKey {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apiKey': json['apiKey'],
        'id': json['id'],
        'created': json['created'],
        'name': json['name'],
        'kind': MachineKindFromJSON(json['kind']),
    };
}

export function MachineAPIKeyToJSON(value?: MachineAPIKey | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apiKey': value.apiKey,
        'id': value.id,
        'created': value.created,
        'name': value.name,
        'kind': MachineKindToJSON(value.kind),
    };
}


