/* tslint:disable */
/* eslint-disable */
/**
 * Infra API
 * Infra REST API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum MachineKind {
    Api = 'api',
    Client = 'client'
}

export function MachineKindFromJSON(json: any): MachineKind {
    return MachineKindFromJSONTyped(json, false);
}

export function MachineKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): MachineKind {
    return json as MachineKind;
}

export function MachineKindToJSON(value?: MachineKind | null): any {
    return value as any;
}

