/* tslint:disable */
/* eslint-disable */
/**
 * Infra API
 * Infra REST API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MachineAPIKeyCreateRequest
 */
export interface MachineAPIKeyCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof MachineAPIKeyCreateRequest
     */
    name: string;
}

export function MachineAPIKeyCreateRequestFromJSON(json: any): MachineAPIKeyCreateRequest {
    return MachineAPIKeyCreateRequestFromJSONTyped(json, false);
}

export function MachineAPIKeyCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MachineAPIKeyCreateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function MachineAPIKeyCreateRequestToJSON(value?: MachineAPIKeyCreateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}


