/* tslint:disable */
/* eslint-disable */
/**
 * Infra API
 * Infra REST API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ProviderKind {
    Okta = 'okta'
}

export function ProviderKindFromJSON(json: any): ProviderKind {
    return ProviderKindFromJSONTyped(json, false);
}

export function ProviderKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderKind {
    return json as ProviderKind;
}

export function ProviderKindToJSON(value?: ProviderKind | null): any {
    return value as any;
}

