/* tslint:disable */
/* eslint-disable */
/**
 * Infra API
 * Infra REST API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum RoleKind {
    Role = 'role',
    ClusterRole = 'cluster-role'
}

export function RoleKindFromJSON(json: any): RoleKind {
    return RoleKindFromJSONTyped(json, false);
}

export function RoleKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleKind {
    return json as RoleKind;
}

export function RoleKindToJSON(value?: RoleKind | null): any {
    return value as any;
}

