/* tslint:disable */
/* eslint-disable */
/**
 * Infra API
 * Infra REST API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SourceOkta
 */
export interface SourceOkta {
    /**
     * 
     * @type {string}
     * @memberof SourceOkta
     */
    apiToken: string;
}

export function SourceOktaFromJSON(json: any): SourceOkta {
    return SourceOktaFromJSONTyped(json, false);
}

export function SourceOktaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceOkta {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apiToken': json['apiToken'],
    };
}

export function SourceOktaToJSON(value?: SourceOkta | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apiToken': value.apiToken,
    };
}


