/* tslint:disable */
/* eslint-disable */
/**
 * Infra API
 * Infra REST API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SourceOkta,
    SourceOktaFromJSON,
    SourceOktaFromJSONTyped,
    SourceOktaToJSON,
} from './';

/**
 * 
 * @export
 * @interface Source
 */
export interface Source {
    /**
     * 
     * @type {string}
     * @memberof Source
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof Source
     */
    created: number;
    /**
     * 
     * @type {number}
     * @memberof Source
     */
    updated: number;
    /**
     * 
     * @type {SourceOkta}
     * @memberof Source
     */
    okta?: SourceOkta;
}

export function SourceFromJSON(json: any): Source {
    return SourceFromJSONTyped(json, false);
}

export function SourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Source {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'created': json['created'],
        'updated': json['updated'],
        'okta': !exists(json, 'okta') ? undefined : SourceOktaFromJSON(json['okta']),
    };
}

export function SourceToJSON(value?: Source | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'created': value.created,
        'updated': value.updated,
        'okta': SourceOktaToJSON(value.okta),
    };
}


