name: build

on:
  workflow_call:
    inputs:
      RELEASE_NAME:
        type: string
        required: true

jobs:
  binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm install
          npm run build
          npm run export
        working-directory: ui
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
      - uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --skip-publish --snapshot
        env:
          RELEASE_NAME: ${{ inputs.RELEASE_NAME }}
      - uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: dist/

  helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v1
      - run: |
          helm package -d helm helm/charts/* --version ${{ inputs.RELEASE_NAME }} --app-version ${{ inputs.RELEASE_NAME }}
      - uses: actions/upload-artifact@v3
        with:
          name: helm
          path: |
            helm/index.yaml
            helm/*.tgz
