name: push

on:
  push:
    branches:
      - main

env:
  TELEMETRY_WRITE_KEY: ${{ secrets.TELEMETRY_WRITE_KEY }}
  CRASH_REPORTING_DSN: ${{ secrets.CRASH_REPORTING_DSN }}

jobs:
  push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: make docker tag=$GITHUB_REF_NAME
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
