name: Close stale issues and pull requests

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: Message to comment on stale issues. If none provided, will not mark issues stale.
          stale-pr-message: Message to comment on stale PRs. If none provided, will not mark PRs stale.
          close-issue-message: This issue was closed because it has been stalled for 5 days with no activity.
          close-pr-message: This PR was closed because it has been stalled for 10 days with no activity.
          days-before-issue-stale: 60
          days-before-issue-close: 7
          days-before-pr-stale: 90
          days-before-pr-close: 14
          exempt-all-pr-assignees: true
